-- DEPRECATED LEGACY FILE
--
-- This file no longer represents the live production database accurately.
-- Production has drifted beyond this one-file schema, especially in `projects`.
--
-- Do NOT use this file as the source of truth for new environments.
-- Use:
--   1) supabase/DB_BASELINE.md
--   2) supabase/archive/schema-legacy-2026-08-23.sql
--   3) supabase/migrations/*.sql
--
-- This file is kept only as a historical reference.

-- Original legacy contents moved to:
-- supabase/archive/schema-legacy-2026-08-23.sql
